FROM php:7.4.7-fpm-alpine

WORKDIR /var/www

RUN rm -rf /var/www/html

# Utiliza a imagem 'builder' para copiar os arquivos do Laravel
COPY --from=builder /var/www/laravel .

# Cria um link simbólico de 'public' para 'html'
RUN ln -s public html

# Corrige o comando 'chow' para 'chown'
RUN chown -R www-data:www-data /var/www

EXPOSE 9000

CMD ["php-fpm"]
